### ISSUE TITLE
Thanks for keeping this alive.

### ISSUE THREAD

**Issue by TakkoTheBoss** [petermost/Sourcetrail#1]
I was looking to install this tool since I've used it in the past. I noticed it was recently archived and maintenance by original developers was dropped. It's such a good tool, so just wanted to say thanks for that.

**Comment by petermost** [comment]
Thanks :smiley:

**Comment by petermost** [comment]
Cleanup

**Comment by petermost** [comment]
Cleanup

**Comment by TakkoTheBoss** [comment]
@petermost I find myself coming back 7 months later in need of Sourcetrail for a personal project. So yet again, thank you.

**Comment by petermost** [comment]
@TakkoTheBoss You are welcome :relaxed:

**Comment by lyrl** [comment]
Thank you so much. @petermost

**Comment by petermost** [comment]
@lyrl You are welcome ☺️
