### ISSUE TITLE
Broken layout with Qt 6.7.1

### ISSUE THREAD

**Issue by petermost** [petermost/Sourcetrail#11]
@xiota reported in https://github.com/petermost/Sourcetrail/issues/9 a broken layout when using Qt 6.7.1

![image](https://github.com/petermost/Sourcetrail/assets/7533951/6a1c8440-cda6-4de7-bc71-c09b607e275f)

the suggested workaround to copy `<sourcetrail_directory>/bin/app/data/fallback/window_settings.ini` to `~/.config/Sourcetrail/window_settings.ini` resulted in this layout:

![image](https://github.com/petermost/Sourcetrail/assets/7533951/b3bb5b6a-b802-4eda-952b-8ca0ebad69d3)

**Comment by petermost** [comment]
@xiota: So the layout is now correct, but the colors are still wrong?

**Comment by xiota** [comment]
> So the layout is now correct, but the colors are still wrong?

Missing icons, resources, etc.

> I'm wondering about the Version 0.0.0. Did you build from a git repository or from some kind of archive?

git checkout of tag 2024.05.

**Comment by petermost** [comment]
> > So the layout is now correct, but the colors are still wrong?
> 
> Missing icons, resources, etc. This is why I think file locations may have changed.
> 

I only ever tested it from the `app` directory inside the build directory. What does it look like when you start it from the `app` directory? But before you start it, please delete the `~/.config/Sourcetrail` directory, so the configuration files are recreated on startup.

**Comment by petermost** [comment]
> @xiota reported in #9 a broken layout when using Qt 6.7.1
> 
With the latest commit 216704d350aa9df7112cac460ffd05610d5ba696 the vcpkg-build is linking (statically) against Qt 6.7.1 and I can't reproduce the described broken layout.

**Comment by xiota** [comment]
I haven't looked at this because rebuilding clang and llvm takes a long time, which makes an already slow build take even longer.  Now it looks like Qt also needs to be rebuilt from scratch so it can be statically linked?

You've also made changes to the build scripts.  Some files that were used during install are now gone.

I am not going down this rabbit hole.

The AUR package is staying at 2023.11 for the time being.

**Comment by petermost** [comment]
> I haven't looked at this because rebuilding clang and llvm takes a long time, which makes an already slow build take even longer. Now it looks like Qt also needs to be rebuilt from scratch so it can be statically linked?
> 
This was always the case for the '**vcpkg-build**', but the '**system-build**' is linking dynamically and only the '**system-build**' is meant for Linux distributions like archlinux!

I only mentioned the 'vcpkg-build' because vcpkg already provides Qt 6.7.1 where as Kubuntu 24.04 provides Qt 6.4.2. And with the vcpkg-build (Qt 6.7.1) I was not able to reproduce the broken layout.

> You've also made changes to the build scripts. Some files that were used during install are now gone.
> 
I'm not experienced in packaging for Linux distributions, so I need more information as to **what** files are missing and **why** are they needed?

**Comment by petermost** [comment]
I cannot reproduce the layout problem with Qt 6.7.1, so I'm closing this issue.

**Comment by xiota** [comment]
FYI: Bug trackers are unreliable when devs close bugs that aren't actually fixed.

**Comment by petermost** [comment]
What do you mean by that?

**Comment by xiota** [comment]
I mean the bug tracker becomes a useless mess when devs habitually close bugs that aren't fixed.

1. The closed status of issues is meaningless.  The bugs may or may not actually be fixed.
2. Users have difficulty finding related bugs, so open new bug reports, which are likely to be closed unfixed or as duplicates.
3. Numerous duplicate closed reports scatters relevant information, making the problem more difficult to fix, if anyone even wants to try.

**Comment by petermost** [comment]
> Also, you closed as "won't fix". Which means you intend to do nothing about the broken layout even if you're able to reproduce it later.

That was a mistake on my side. I have not quite figured out yet how to close issues with the correct label. But I labeled it afterwards with "cannot reproduce" and it shows up with the correct label in the issues overview.

**Comment by petermost** [comment]
But if we are already discussing "correct handling" of issues, I would like to ask you: 
- Provide more information for a problem you encounter, so I don't have to ask all the time for more information. Don't **assume** that your **short** comments are self explanatory.
- Add your information/comments to the correct issue or open a new one, so I don't have to copy comments around.

Having said that: I still want to help with the support for archlinux.

**Comment by xiota** [comment]
> I still want to help with the support for archlinux.

You recently bumped requirements to clang 18.  So Arch Linux is out for now.

**Comment by petermost** [comment]
> 1. I didn't open this as a new issue.  You did.
> 
That's correct, because you didn't open a new issue for this new problem.
> 2. You didn't ask for additional information to replicate the problem.
>
I did in https://github.com/petermost/Sourcetrail/issues/11#issuecomment-2165485444

> 3. You know the general environment and method I'm using, but used an opposite method.  That cannot be considered a bonafide attempt to replicate the issue.

I know **nothing** of your environment except that you are on Arch Linux, where as I'm working on (K)ubuntu 22.04 and Windows 10. 

On (K)ubuntu 22.04 only Qt 6.4.2 is available. But I have no reason to assume that a statically linked Qt 6.7.1 (vcpkg-build) is behaving differently then a dynamically linked Qt 6.7.1 (Arch Linux)

**Comment by xiota** [comment]
That comment does not ask for information to help you replicate the issue.  It asks me to run the program a particular way that is complicated to do because I am building packages.  This you should be aware of because you contacted me through the AUR page.

If you wanted to attempt to replicate the issue, you could have asked for the PKGBUILD, which you could use to build the package in a VM.

**Comment by petermost** [comment]
> That comment does not ask for information to help you replicate the issue. It asks me to run the program a particular way that is complicated to do because I am building packages. This you should be aware of because you contacted me through the AUR page.
> 
You should've mentioned that :wink: 

> If you wanted to attempt to replicate the issue, you could have asked for the PKGBUILD, which you could use to build the package in a VM.

If you **know** that I need the PKGBUILD, then why didn't you already attach it? :wink:

**Comment by xiota** [comment]
I've had enough of this.  As already stated, AUR package is on 2023.11 until further notice.  As already stated, you've bumped minimum requirements past what is currently available on Arch.  So there's no point wasting time trying to build this.  I'll take try again when clang 18 is available on Arch, assuming you haven't bumped to 19.
