### ISSUE TITLE
Wrong tag: 2027.7.0

### ISSUE THREAD

**Issue by xiota** [petermost/Sourcetrail#13]
Need to delete and retag.

**Comment by petermost** [comment]
Can you please explain why this and "all subsequent tags" are wrong or broken?

**Comment by petermost** [comment]
My guess is, that the typo is the problem. I renamed the tag from ~~2027.7.0~~ to 2024.7.0

**Comment by xiota** [comment]
For this tag, I assumed 2027 is a typo.

As for other tags, they're either unbuildable (different reasons) or produce incorrect output.

Since 2023.11 is still working, it's not urgent for me to try to fix.

**Comment by petermost** [comment]
If you would provide more information, we could determine whether this is an archlinux problem or a problem in Sourcetrail. But please do so in the correct issue [AUR Package](https://github.com/petermost/Sourcetrail/issues/9) which is about packaging.
