### ISSUE TITLE
Failed to build on Windows11 with mismatched "boost_system" version

### ISSUE THREAD

**Issue by Joshua1023** [petermost/Sourcetrail#17]
Thanks for maintaining Sourcetrail and updating it to support clang 18.

I succeeded in building Sourcetrail on Ubuntu 24.04. However, when I built it on Windows11 with vcpkg, I met a problem.

I ran:
```
$ git clone https://github.com/petermost/Sourcetrail.git --recurse-submodules --config core.symlinks=true
$ cd Sourcetrail
$ git checkout 2024.8.2
$ cmake --preset vcpkg-ninja-release
```
After a long time building process, I met the problem:
```
PS C:\Users\dell\sourcetrail\Sourcetrail> cmake --preset vcpkg-ninja-release
Preset CMake variables:

  BUILD_CXX_LANGUAGE_PACKAGE="ON"
  BUILD_JAVA_LANGUAGE_PACKAGE="ON"
  BUILD_PYTHON_LANGUAGE_PACKAGE="OFF"
  BUILD_UNIT_TESTS_PACKAGE="ON"
  CMAKE_BUILD_TYPE="Release"
  CMAKE_EXPORT_COMPILE_COMMANDS="FALSE"
  CMAKE_TOOLCHAIN_FILE="C:/Users/dell/sourcetrail/Sourcetrail/vcpkg/scripts/buildsystems/vcpkg.cmake"
  CMAKE_VERBOSE_MAKEFILE="FALSE"

-- Vcpkg Build
-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exeAll requested packages are currently installed.
Total install time: 300 ns

...

-- Running vcpkg install - done
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package):
  Could not find a configuration file for package "boost_system" that exactly
  matches requested version "1.85.0".

  The following configuration files were considered but not accepted:

    C:/Users/dell/sourcetrail/build/vcpkg-ninja-release/vcpkg_installed/custom-x64-windows-static-md/share/boost_system/boost_system-config.cmake, version: 1.85.0 (64bit)

Call Stack (most recent call first):
  C:/Users/dell/sourcetrail/build/vcpkg-ninja-release/vcpkg_installed/custom-x64-windows-static-md/share/boost/BoostConfig.cmake:67 (find_package)
  C:/Users/dell/sourcetrail/build/vcpkg-ninja-release/vcpkg_installed/custom-x64-windows-static-md/share/boost/BoostConfig.cmake:128 (boostcfg_find_component)
  C:/Users/dell/sourcetrail/build/vcpkg-ninja-release/vcpkg_installed/custom-x64-windows-static-md/share/boost/vcpkg-cmake-wrapper.cmake:3 (_find_package)
  vcpkg/scripts/buildsystems/vcpkg.cmake:811 (include)
  C:/Users/dell/sourcetrail/CMake/share/cmake-3.28/Modules/FindBoost.cmake:594 (find_package)
  C:/Users/dell/sourcetrail/build/vcpkg-ninja-release/vcpkg_installed/custom-x64-windows-static-md/share/boost/vcpkg-cmake-wrapper.cmake:3 (_find_package)
  vcpkg/scripts/buildsystems/vcpkg.cmake:811 (include)
  CMakeLists.txt:88 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by petermost** [comment]
Very strange. The CMakeLists.txt:88 requests the Boost version "1.83" and the error message complains about not able to find "1.85.0". But since you did a fresh pull, I'm assuming there aren't any local changes?

**Comment by Joshua1023** [comment]
> Very strange. The CMakeLists.txt:88 requests the Boost version "1.83" and the error message complains about not able to find "1.85.0". But since you did a fresh pull, I'm assuming there aren't any local changes?

Yes, the working tree is clean.

And I checked the files on Ubuntu 24.04. In `vcpkg/packages/boost-system_custom-x64-static-md/CONTROL`:
```
Package: boost-system
Version: 1.85.0
Port-Version: 1
Depends: boost-assert, boost-cmake, boost-config, boost-headers, boost-throw-exception, boost-variant2, boost-winapi
Architecture: custom-x64-static-md
Multi-Arch: same
Abi: b821c3df8774be4d56374a88da20acfb4f04f655ee695c45b1fe1393fdc9e012
Description: Boost system module
```

Does this mean the version "1.85.0" of "boost-system" was also used when building Sourcetrail on Linux?

**Comment by petermost** [comment]
> 
> Does this mean the version "1.85.0" of "boost-system" was also used when building Sourcetrail on Linux?

Looks like it, but for Boost that's OK, because the versions are usually backward compatible.

Unfortunately I can't reproduce the error, so I have some "shots in the dark" questions:
- Do you use separate directories for Linux/Windows?
- On Windows: Do you have a separate Boost installation?
- Does your CMakeLists.txt:86 contain the line `find_package(Boost 1.83 REQUIRED COMPONENTS`?

Can you attach or post the **complete** output of `cmake --preset vcpkg-ninja-release`? 
It's **not** necessary to do a rebuild! Just run the command again.

**Comment by Joshua1023** [comment]
> > Does this mean the version "1.85.0" of "boost-system" was also used when building Sourcetrail on Linux?
> 
> Looks like it, but for Boost that's OK, because the versions are usually backward compatible.
> 
> Unfortunately I can't reproduce the error, so I have some "shots in the dark" questions:
> 
> * Do you use separate directories for Linux/Windows?
> * On Windows: Do you have a separate Boost installation?
> * Does your CMakeLists.txt:86 contain the line `find_package(Boost 1.83 REQUIRED COMPONENTS`?
> 
> Can you attach or post the **complete** output of `cmake --preset vcpkg-ninja-release`? It's **not** necessary to do a rebuild! Just run the command again.

- Yes. The repo is cloned to `~/Sourcetrail` on Linux and to `C:/Users/dell/sourcetrail/Sourcetrail` on Windows
- Yes. I built origin Sourcetrail with Visual Studio refer to [https://github.com/CoatiSoftware/Sourcetrail#building-the-base-application](https://github.com/CoatiSoftware/Sourcetrail#building-the-base-application). So I installed Boost 1.67.0 ([https://sourceforge.net/projects/boost/files/boost-binaries/1.67.0/boost_1_67_0-msvc-14.1-64.exe/download](https://sourceforge.net/projects/boost/files/boost-binaries/1.67.0/boost_1_67_0-msvc-14.1-64.exe/download))
- Since I checkout `2024.8.2`,  CMakeLists.txt:88 contains the line `find_package(Boost 1.83 REQUIRED COMPONENTS`

Now I'm away from the machine of building Sourcetrail. I will attach the complete output ASAP.

**Comment by petermost** [comment]
> 
> Yes. I built origin Sourcetrail with Visual Studio refer to https://github.com/CoatiSoftware/Sourcetrail#building-the-base-application. So I installed Boost 1.67.0 (https://sourceforge.net/projects/boost/files/boost-binaries/1.67.0/boost_1_67_0-msvc-14.1-64.exe/download)
> 

I suspect, that this might be the problem. This would be, what I call a 'System Build' under Windows, and as I wrote here  ['I didn't/don't test it.'](https://github.com/petermost/Sourcetrail#user-content-windows) and therefore don't support it. 

So, please uninstall Boost 1.67.0 or otherwise make sure that cmake is not picking up that installation and try again.

The same goes for any other library you might have installed! :wink:  The 'Vcpkg Build' is building everything that is needed to build Sourcetrail.

**Comment by petermost** [comment]
> 
> So, please uninstall Boost 1.67.0 or otherwise make sure that cmake is not picking up that installation and try again.
> 
> The same goes for any other library you might have installed! 😉 The 'Vcpkg Build' is building everything that is needed to build Sourcetrail.

... and regenerate the `CMakeCache.txt`. If in doubt run `cmake --fresh --preset vcpkg-ninja-release`

**Comment by Joshua1023** [comment]
After I uninstalled Strawberry Perl that I used for building the origin Sourcetrail, everything went well. Now I'll close this issue.
