### ISSUE TITLE
ld.exe: cannot find /ENTRY:mainCRTStartup: No such file or directory

### ISSUE THREAD

**Issue by Joshua1023** [petermost/Sourcetrail#18]
Hello again!

`cmake --preset vcpkg-ninja-release` was successful.
However, I met another problem when I ran `cmake --build .`:
```
FAILED: app/sourcetrail_indexer.exe
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\Users\dell\Sourcetrail\vcpkg\downloads\tools\perl\5.38.0.1\c\bin\c++.exe -O3 -DNDEBUG /ENTRY:"mainCRTStartup" /SUBSYSTEM:WINDOWS @CMakeFiles\Sourcetrail_indexer.rsp -o app\sourcetrail_indexer.exe -Wl,--out-implib,src\indexer\libsourcetrail_indexer.dll.a -Wl,--major-image-version,0,--minor-image-version,0  && C:\WINDOWS\system32\cmd.exe /C "cd /D C:\Users\dell\build\vcpkg-ninja-release\src\indexer && C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file C:/Users/dell/Sourcetrail/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/dell/build/vcpkg-ninja-release/app/sourcetrail_indexer.exe -installedDir C:/Users/dell/build/vcpkg-ninja-release/vcpkg_installed/custom-x64-windows-static-md/bin -OutVariable out""
C:/Users/dell/Sourcetrail/vcpkg/downloads/tools/perl/5.38.0.1/c/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find /ENTRY:mainCRTStartup: No such file or directory
C:/Users/dell/Sourcetrail/vcpkg/downloads/tools/perl/5.38.0.1/c/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find /SUBSYSTEM:WINDOWS: No such file or directory
```

I attached the outputs of the commands:
[output_preset.txt](https://github.com/user-attachments/files/16635815/output_preset.txt)
[output_build.txt](https://github.com/user-attachments/files/16643383/output_build.txt)

**Comment by petermost** [comment]
Your development environment seems to be messed up. See for example output_preset.txt:241
`-- Check for working CXX compiler: C:/Users/dell/Sourcetrail/vcpkg/downloads/tools/perl/5.38.0.1/c/bin/c++.exe - skipped`
where it detects some compiler from perl. Where as on my system it looks like this:
`-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped`
For reference I attach my output from `cmake --fresh --preset vcpkg-ninja-release`
[cmake_fresh_preset.log](https://github.com/user-attachments/files/16749837/cmake_fresh_preset.log)

Are you using the 'x64 Native Tools Command Prompt for VS 2022' to execute the cmake command?

**Comment by Joshua1023** [comment]
Since README does not mention that Visual Studio is required, I did not use VS to build Sourcetrail. That's the problem. After I used VS instead, I built Sourcetrail successfully.
