### ISSUE TITLE
Whats the difference to OpenSourceSourceTrail?

### ISSUE THREAD

**Issue by hardliner66** [petermost/Sourcetrail#20]
I know sourcetrail from before it was archived and wanted to give it a try again, but there are two somewhat active forks now. This and https://github.com/OpenSourceSourceTrail/Sourcetrail. Whats the difference? Why not work together? I'm a bit confused about which version to use and it would be cool to know why theres two versions :D

**Comment by petermost** [comment]
The biggest differences, from **my point of view**, are:
- Downloadable releases
- New features ([CHANGELOG.md](https://github.com/petermost/Sourcetrail/blob/master/CHANGELOG.md))
- Indexer support for C++. Java, Python
- Updates to the underlying libraries (Qt6, Clang-18, Boost-1.83, etc.)
- User support (Issues)

I can't tell you what the other project tries to achieve. Ask them 😉
