### ISSUE TITLE
cannot compile the documented way

### ISSUE THREAD

**Issue by Iampotato204** [petermost/Sourcetrail#3]
Linux (Debian), all dependencies installed, including ninja (ninja-build package)
Using the README guideline gives the following output:

Preset CMake variables:

  BUILD_CXX_LANGUAGE_PACKAGE="ON"
  BUILD_JAVA_LANGUAGE_PACKAGE="ON"
  CMAKE_BUILD_TYPE="Release"
  CMAKE_EXPORT_COMPILE_COMMANDS="TRUE"
  CMAKE_TOOLCHAIN_FILE="/home/user/Sourcetrail/vcpkg/scripts/buildsystems/vcpkg.cmake"
  CMAKE_VERBOSE_MAKEFILE="TRUE"

Vcpkg Build
-- Version: 2023.11.4
-- setting up the buildtype for versioning
CMake Error at /usr/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:130 (message):
  Could not find toolchain file:
  /home/user/Sourcetrail/vcpkg/scripts/buildsystems/vcpkg.cmake
Call Stack (most recent call first):
  CMakeLists.txt:57 (project)

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred

**Comment by Iampotato204** [comment]
![sourcetrail-bug1_ninja](https://github.com/petermost/Sourcetrail/assets/69730358/dda85829-f8aa-463e-a233-acf964b3ad80)

**Comment by petermost** [comment]
How did you clone the repository?

**Comment by Iampotato204** [comment]
I used git ("git clone ...")
Following documentation, I used "cmake --preset vcpkg-ninja-release", which resulted into the described error

**Comment by petermost** [comment]
It doesn't help if you leave out the important information of how you cloned the repository.

I can reproduce the error if I clone **without** the submodules. So you probably forgot the `--recurse-submodules` switch when cloning.
