### ISSUE TITLE
<question> <invalid> Apparently, no indexing is being done 

### ISSUE THREAD

**Issue by Iampotato204** [petermost/Sourcetrail#4]
When I built the project using:
//
    cmake -S Sourcetrail -B Sourcetrail_build
    cd Sourcetrail_build
    make
//
... then running the project resulted in failing to index any file. Also, it required me to input some custom_command(when creating the project), could you briefly tell what exactly it is and how to setup it? 
This command was obligatory to input for some reason (it didn`t have the star!)

**Comment by petermost** [comment]
You need to enable at least one language support e.g.:
`cmake -S Sourcetrail -B Sourcetrail_build -D BUILD_CXX_LANGUAGE_PACKAGE=ON`
