### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by dkasak** [petermost/Sourcetrail#5]
I was thrilled to see Sourcetrail being kept at least somewhat alive, but my hopes were a bit dampened when I saw Python support was ripped out. I'm somewhat interested in keeping that in, potentially even offering a helping hand, time permitting.

So I'm wondering whether the removal was just to reduce maintenance burden by removing a feature you personally (@petermost) don't need or was there significant bitrot, such that fixing it would've required too much effort?

Many thanks for the work so far!

**Comment by petermost** [comment]
Thank you for your kind words :smile:

And yes, I removed the Python support because I don't need it and don't have time to maintain it. But if you or somebody else wants to provide pull requests, then I would try to integrate them.

**Comment by petermost** [comment]
I'm closing this for now, but as I wrote: If somebody wants to help then please let me know.
I should also mention, that the source files for the python support have not been removed, they are just not integrated in the current build.

**Comment by petermost** [comment]
I've reintegrated the Python language package source files in commit 23f38a7f42221e5b57b29aca0c1fb6d45c9d1b15 but left the code to download the Python indexer disabled. See the [CMakeLists.txt](https://github.com/petermost/Sourcetrail/blob/master/src/lib_python/CMakeLists.txt)

**Comment by petermost** [comment]
Fixed now also the download of the Python indexer with commit a77b8493521d2ff82f78770946934fc31dd61166.
