### ISSUE TITLE
Sourcetrail does not index the deduced type of "auto"

### ISSUE THREAD

**Issue by petermost** [petermost/Sourcetrail#8]
The original issue [feature request: expand C++ "auto" type](https://github.com/CoatiSoftware/Sourcetrail/issues/1041) doesn't go into details what is wanted here, but from own experience it seems indexing handles **all** auto types as a single type. It would be much more helpful to index the deduced type and ideally also consider these usages of [auto](https://en.cppreference.com/w/cpp/keyword/auto): 

1. auto placeholder type specifier
1. Function declaration with trailing return type 
1. Structured binding declaration 
1. Abbreviated function template 
1. Explicit cast to a prvalue copy 

@bam80: Is this what you had in mind?

**Comment by bam80** [comment]
Sorry I don't remember.
Are you going to resurrect Sourcetrail? That would be awesome.

I'm interested in the story behind that.

**Comment by petermost** [comment]
> Are you going to resurrect Sourcetrail? That would be awesome.

Well, look at the commits and judge for yourself :wink:

> I'm interested in the story behind that.

Not much to tell. I was a costumer for the commercial product and used and use it very successfully in my freelancer projects. After the Coati company decided to stop working on it, I thought maybe somebody else will continue it, but that didn't happen. Because this is *the* tool I basically was waiting for years (and I currently have the time), I decided I give it a try.

**Comment by bam80** [comment]
Great, I wish you good luck!

**Comment by petermost** [comment]
Added indexing of the deduced type of auto variables with 6e6d3a2fa9534ed2aa03dfa21022a7300fdf9b0a

**Comment by petermost** [comment]
Added indexing of abbreviated function templates with https://github.com/petermost/Sourcetrail/commit/d347ef1a8918dc3b23f88d954624e8780581ae71

**Comment by petermost** [comment]
Added indexing of auto prvalue casts with https://github.com/petermost/Sourcetrail/commit/f3cf4ebbb0d8da22d1c98176315ad520de06d9b5

**Comment by petermost** [comment]
As far as I can see all `auto` usages should now be recognized and indexed.
