### ISSUE TITLE
Arch Linux Package

### ISSUE THREAD

**Issue by xiota** [petermost/Sourcetrail#9]
I saw [your comment](https://aur.archlinux.org/packages/sourcetrail#comment-975203) on the AUR page.  As far as formatting, the comment boxes use markdown.  Also, there are not separate `-dev` packages on Arch.  Nearly all libraries include headers and other files needed for development.

The AUR package is currently out of date and does not build with current Arch packages.  I am unable to update to the recently tagged release because several llvm/clang libraries are missing.

Here is output from my most recent attempt, using `rocm-llvm`:
```
ld.lld: error: undefined symbol: typeinfo for clang::tooling::CompilationDatabase
>>> referenced by ld-temp.o
>>>               lto.tmp:(typeinfo for CxxCompilationDatabaseSingle)
>>> did you mean: vtable for clang::tooling::CompilationDatabase
>>> defined in: /opt/rocm/lib/llvm/lib/libclangTooling.a(CompilationDatabase.cpp.o)

ld.lld: error: undefined symbol: typeinfo for clang::ASTFrontendAction
>>> referenced by ld-temp.o
>>>               lto.tmp:(typeinfo for ASTAction)
>>> did you mean: vtable for clang::ASTFrontendAction
>>> defined in: /opt/rocm/lib/llvm/lib/libclangFrontend.a(FrontendAction.cpp.o)

ld.lld: error: undefined symbol: typeinfo for clang::CommentHandler
>>> referenced by ld-temp.o
>>>               lto.tmp:(typeinfo for CommentHandler)

ld.lld: error: undefined symbol: typeinfo for clang::ASTConsumer
>>> referenced by ld-temp.o
>>>               lto.tmp:(typeinfo for ASTConsumer)

ld.lld: error: undefined symbol: typeinfo for clang::TextDiagnosticPrinter
>>> referenced by ld-temp.o
>>>               lto.tmp:(typeinfo for CxxDiagnosticConsumer)

ld.lld: error: undefined symbol: typeinfo for clang::PPCallbacks
>>> referenced by ld-temp.o
>>>               lto.tmp:(typeinfo for PreprocessorCallbacks)

ld.lld: error: undefined symbol: typeinfo for clang::tooling::FrontendActionFactory
>>> referenced by ld-temp.o
>>>               lto.tmp:(typeinfo for SingleFrontendActionFactory)

ld.lld: error: undefined symbol: typeinfo for clang::GeneratePCHAction
>>> referenced by ld-temp.o
>>>               lto.tmp:(typeinfo for GeneratePCHAction)
```

**Comment by petermost** [comment]
Sourcetrail depends on clang/LLVM 17 which seems is not available in Arch according to this page:
https://aur.archlinux.org/packages
It finds clang15/llvm15 and llvm18 (without clang18!) which makes me wonder, how can you get [linker errors](https://aur.archlinux.org/packages/sourcetrail#comment-961404) with clang/llvm 16-17 if these packages are not listed/available?

What I also don't understand: The CMakeLists.txt specifically requires clang 17. So how did you get passed the cmake requirement?

And finally: What clang/LLVM version is included in rocm-llvm?

**Comment by xiota** [comment]
Official Arch packages can be found at https://archlinux.org/packages/

The packages listed at https://aur.archlinux.org/packages are part of the Arch User Repository (AUR).  It's a collection of packaging scripts maintained by users.

Clang/LLVM 14, 16, and 17 are in the official repos.  `rocm-llvm` has Clang/LLVM 17.  None of the packages in the official repos have all of the AST libraries.

**Comment by petermost** [comment]
> None of the packages in the official repos have all of the AST libraries.

OK, but if that's the case, then what can I do to help?

Shouldn't this then communicated to the maintainers of the clang/LLVM packages on the Arch Linux side?

**Comment by xiota** [comment]
Nothing to do as far as the AST libraries are concerned.  Opened this issue solely to respond to your comment and didn't want to clutter the AUR page.

**Comment by petermost** [comment]
Could the [Vcpkg Build](https://github.com/petermost/Sourcetrail#vcpkg-build) be an option? It, among others, builds clang/LLVM from source and then links statically to the libraries.

**Comment by xiota** [comment]
I'd prefer to leave rebuilding clang/llvm as a last resort.  I will ask Arch devs about the missing files.

**Comment by xiota** [comment]
Not compatible with Qt 6.7.1?

![sourcetrail](https://github.com/petermost/Sourcetrail/assets/8353098/93145ea8-8beb-44e6-b5f3-2ab29896a7b8)

**Comment by petermost** [comment]
The only time I have seen this broken layout, is when the `~/.config/Sourcetrail/window_settings.ini` is missing. if you copy `<sourcetrail_directory>/bin/app/data/fallback/window_settings.ini` to the mentioned directory, then the layout should be fixed.

**Comment by petermost** [comment]
I have created a new issue https://github.com/petermost/Sourcetrail/issues/11 for the broken layout.

**Comment by petermost** [comment]
> Seems like file paths have changed from 2023.11? Previous paths are:
> 
> ```
> /opt/sourcetrail/bin
> /opt/sourcetrail/data
> ```
> 
> Where do files go now?

I'm not aware that I have defined anywhere an installation path except for my attempt to create a debian package at the end of the toplevel `CMakeLists.txt`. But I have not tested it extensively because there was no demand for it.

**Comment by petermost** [comment]
Copying https://github.com/petermost/Sourcetrail/issues/11#issuecomment-2179720119 from @xiota here, because this is the correct issue for it:

> You've also made changes to the build scripts. Some files that were used during install are now gone.
> ...
> The AUR package is staying at 2023.11 for the time being.

**Comment by petermost** [comment]
Copying my response:
> I'm not experienced in packaging for Linux distributions, so I need more information as to **what** files are missing and **why** are they needed?

**Comment by xiota** [comment]
The problem is you moved and deleted files without knowing what they were for.  At this point, I'm not sure whether trying to fix this repo would be easier than forking from 2023.11.

**Comment by petermost** [comment]
Do I really have to repeat my response? **Which** files? I'm happy to reintegrate them.

**Comment by xiota** [comment]
This is a complicated project.  Figuring out what's been changed would take a while.  As already stated, there's no urgency to do a full review because 2023.11 is still usable.  I haven't decided whether fixing or forking would be preferable.

**Comment by petermost** [comment]
I consider this issue completed, because there is now a separate repository which tracks the necessary changes for building Sourcetrail on Arch Linux. 

Please see here for further information: https://aur.archlinux.org/packages/sourcetrail
